# Generated by Django 2.2.7 on 2019-12-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=120, verbose_name='Телефон')),
                ('address', models.CharField(max_length=120, verbose_name='Телефон')),
            ],
        ),
    ]
