# Generated by Django 2.2.7 on 2019-12-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.CharField(max_length=4, null=True, verbose_name='Количество Людей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=120, verbose_name='Домашний Адрес'),
        ),
    ]
