# Generated by Django 2.2.7 on 2019-12-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191203_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.IntegerField(max_length=4, verbose_name='Количество Людей'),
        ),
    ]
