# Generated by Django 2.2.7 on 2019-12-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191203_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.CharField(max_length=120, verbose_name='Количество Людей'),
        ),
    ]
