# Generated by Django 2.2.7 on 2019-12-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_booking_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrive',
            field=models.CharField(max_length=120, null=True, verbose_name='Дата приезда'),
        ),
        migrations.AddField(
            model_name='booking',
            name='depart',
            field=models.CharField(max_length=120, null=True, verbose_name='Дата отъезда'),
        ),
    ]
