# Generated by Django 2.2.7 on 2019-12-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20191205_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='arrive',
            new_name='ar',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='depart',
            new_name='dt',
        ),
    ]
