# Generated by Django 2.2.7 on 2019-12-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20191205_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ar',
            field=models.DateField(default='', max_length=120, verbose_name='Дата Приезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dt',
            field=models.DateField(default='', max_length=120, verbose_name='Дата Отъезда'),
        ),
    ]
