# Generated by Django 2.2.7 on 2019-12-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20191205_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ar',
            new_name='arrive',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='dt',
            new_name='depart',
        ),
    ]
