# Generated by Django 2.2.7 on 2019-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20191205_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='arrive',
        ),
        migrations.AlterField(
            model_name='booking',
            name='depart',
            field=models.CharField(max_length=120, verbose_name='Отьезд'),
        ),
    ]
