# Generated by Django 2.2.7 on 2019-12-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20191205_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='people',
        ),
    ]
