# Generated by Django 2.2.7 on 2019-12-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_remove_booking_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.CharField(max_length=120, null=True, verbose_name='Количество Человек'),
        ),
    ]
