# Generated by Django 2.2.7 on 2019-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_booking_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='depart',
            field=models.CharField(max_length=120, null=True, verbose_name='Отьезд'),
        ),
    ]
