# Generated by Django 2.2.7 on 2019-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20191205_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='depart',
            field=models.CharField(default='', max_length=120, null=True, verbose_name='Отьезд'),
        ),
    ]
