# Generated by Django 2.2.7 on 2019-12-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20191205_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='depart',
        ),
    ]
